import type { JobTypeConfig } from '../types'

export const JOB_TYPE_CONFIGS: Record<string, JobTypeConfig> = {
  ML: {
    label: 'Machine Learning',
    color: '#38bdf8',
    fields: [
      { key: 'modelArchitecture', label: 'Model Architecture', type: 'text', placeholder: 'e.g. ResNet-50, Llama-2-7B', required: true },
      { key: 'framework', label: 'Framework', type: 'select', options: [{ value: 'pytorch', label: 'PyTorch' }, { value: 'tensorflow', label: 'TensorFlow' }, { value: 'jax', label: 'JAX' }, { value: 'onnx', label: 'ONNX' }, { value: 'keras', label: 'Keras' }, { value: 'scikit-learn', label: 'Scikit-learn' }], required: true },
      { key: 'task', label: 'Task Type', type: 'select', options: [{ value: 'classification', label: 'Classification' }, { value: 'detection', label: 'Object Detection' }, { value: 'segmentation', label: 'Segmentation' }, { value: 'nlp', label: 'NLP / LLM' }, { value: 'generation', label: 'Generation' }, { value: 'regression', label: 'Regression' }] },
      { key: 'epochs', label: 'Epochs', type: 'number', placeholder: '100', required: true },
      { key: 'batchSize', label: 'Batch Size', type: 'number', placeholder: '32' },
      { key: 'learningRate', label: 'Learning Rate', type: 'text', placeholder: '0.001' },
      { key: 'optimizer', label: 'Optimizer', type: 'select', options: [{ value: 'adam', label: 'Adam' }, { value: 'adamw', label: 'AdamW' }, { value: 'sgd', label: 'SGD' }, { value: 'lion', label: 'Lion' }, { value: 'adafactor', label: 'Adafactor' }] },
      { key: 'lossFunction', label: 'Loss Function', type: 'text', placeholder: 'e.g. cross-entropy, MSE, dice' },
      { key: 'precision', label: 'Precision', type: 'select', options: [{ value: 'fp32', label: 'FP32' }, { value: 'fp16', label: 'FP16' }, { value: 'int8', label: 'INT8' }, { value: 'bf16', label: 'BF16' }] },
      { key: 'numGPUs', label: 'Number of GPUs', type: 'number', placeholder: '1' },
      { key: 'datasetSize', label: 'Dataset Size', type: 'text', placeholder: 'e.g. 100GB, 1M samples' },
      { key: 'validationSplit', label: 'Validation Split', type: 'text', placeholder: 'e.g. 0.2 or 20%' },
    ],
    inputHint: 'Dataset URL or model checkpoint',
    inputPlaceholder: 'https://... or ipfs://...',
    outputHint: 'Expected accuracy / loss threshold, model weights format',
    verificationOptions: [
      { value: 'hash-check', label: 'Weight Hash (off-chain)' },
      { value: 'manual-review', label: 'Manual Review' },
    ],
  },
  ZK: {
    label: 'Zero Knowledge Proof',
    color: '#a78bfa',
    fields: [
      { key: 'circuitType', label: 'Proving System', type: 'select', options: [
        { value: 'groth16', label: 'Groth16' },
        { value: 'plonk', label: 'PLONK' },
        { value: 'stark', label: 'STARK' },
        { value: 'fflonk', label: 'FFLONK' },
        { value: 'sonic', label: 'Sonic' },
        { value: 'marlin', label: 'Marlin' },
        { value: 'spartan', label: 'Spartan' },
        { value: 'bulletproofs', label: 'Bulletproofs' },
        { value: 'halo2', label: 'Halo2' },
        { value: 'supernova', label: 'SuperNOVA' },
        { value: 'nova', label: 'Nova' },
      ], required: true },
      { key: 'language', label: 'DSL / Language', type: 'select', options: [
        { value: 'circom', label: 'Circom' },
        { value: 'noir', label: 'Noir' },
        { value: 'halo2', label: 'Halo2 Rust' },
        { value: 'leo', label: 'Leo (Aleo)' },
        { value: 'cairo', label: 'Cairo (Starkware)' },
        { value: 'lurk', label: 'Lurk (Filecoin)' },
        { value: 'snarky', label: 'Snarky/Pickles (Mina)' },
        { value: 'zokrates', label: 'ZoKrates' },
      ], required: true },
      { key: 'curve', label: 'Curve', type: 'select', options: [
        { value: 'bn254', label: 'BN254' },
        { value: 'bls12-381', label: 'BLS12-381' },
        { value: 'bls12-377', label: 'BLS12-377' },
        { value: 'pallas-vesta', label: 'Pallas / Vesta (Mina)' },
        { value: 'goldilocks', label: 'Goldilocks (Plonky2/3)' },
        { value: 'secp256k1', label: 'secp256k1' },
      ] },
      { key: 'constraintCount', label: 'Constraint Count', type: 'text', placeholder: 'e.g. 100000' },
      { key: 'publicInputs', label: 'Public Inputs', type: 'number', placeholder: '2' },
      { key: 'privateInputs', label: 'Private Inputs', type: 'number', placeholder: '1' },
      { key: 'trustedSetup', label: 'Trusted Setup Requirement', type: 'select', options: [
        { value: 'none', label: 'None (transparent)' },
        { value: 'universal', label: 'Universal (powers of tau)' },
        { value: 'per-circuit', label: 'Per-circuit (CRS)' },
      ] },
    ],
    inputHint: 'Witness file, input.json, circuit WASM / JSON',
    inputPlaceholder: 'Paste input JSON or upload file',
    outputHint: 'proof.json + public.json structure, verification gas estimate',
    verificationOptions: [
      { value: 'zk-proof', label: 'On-chain ZK Proof' },
      { value: 'hash-check', label: 'Hash Check (off-chain)' },
    ],
  },
  Render: {
    label: 'Video / 3D Render',
    color: '#f97316',
    fields: [
      { key: 'engine', label: 'Render Engine', type: 'select', options: [{ value: 'blender', label: 'Blender Cycles / Eevee' }, { value: 'maya', label: 'Maya Arnold' }, { value: 'unreal', label: 'Unreal Engine' }, { value: '3dsmax', label: '3ds Max V-Ray' }, { value: 'cinema4d', label: 'Cinema 4D Redshift' }, { value: 'houdini', label: 'Houdini Mantra / Karma' }], required: true },
      { key: 'samples', label: 'Samples', type: 'number', placeholder: '256' },
      { key: 'resolution', label: 'Resolution', type: 'select', options: [{ value: '1920x1080', label: '1920x1080 (Full HD)' }, { value: '3840x2160', label: '3840x2160 (4K)' }, { value: '7680x4320', label: '7680x4320 (8K)' }, { value: '1280x720', label: '1280x720 (720p)' }, { value: 'custom', label: 'Custom' }], required: true },
      { key: 'outputFormat', label: 'Output Format', type: 'select', options: [{ value: 'png', label: 'PNG' }, { value: 'exr', label: 'EXR (OpenEXR)' }, { value: 'jpg', label: 'JPEG' }, { value: 'mp4', label: 'MP4' }, { value: 'tiff', label: 'TIFF' }] },
      { key: 'frameRange', label: 'Frame Range', type: 'text', placeholder: '1-240' },
      { key: 'fps', label: 'Frames Per Second', type: 'number', placeholder: '24' },
      { key: 'denoiser', label: 'Denoiser', type: 'select', options: [{ value: 'optix', label: 'OptiX (AI)' }, { value: 'openimage', label: 'OpenImageDenoise' }, { value: 'none', label: 'None' }] },
      { key: 'lightBounces', label: 'Max Light Bounces', type: 'number', placeholder: '12' },
      { key: 'transparentBg', label: 'Transparent Background', type: 'select', options: [{ value: 'no', label: 'No (solid bg)' }, { value: 'yes', label: 'Yes (RGBA)' }] },
      { key: 'motionBlur', label: 'Motion Blur', type: 'select', options: [{ value: 'none', label: 'None' }, { value: 'shutter', label: 'Shutter-based' }, { value: 'post', label: 'Post-process' }] },
    ],
    inputHint: 'Blend/Maya/USD file, textures, HDRI',
    inputPlaceholder: 'Upload .blend file or paste URL',
    outputHint: 'Rendered frames format, resolution, quality threshold',
    verificationOptions: [
      { value: 'hash-check', label: 'Frame Hash Check' },
      { value: 'manual-review', label: 'Manual Visual Review' },
    ],
  },
  'AI Inference': {
    label: 'AI Inference',
    color: '#34d399',
    fields: [
      { key: 'modelId', label: 'Model ID / HuggingFace', type: 'text', placeholder: 'meta-llama/Llama-2-7b', required: true },
      { key: 'provider', label: 'Inference Engine', type: 'select', options: [{ value: 'vllm', label: 'vLLM' }, { value: 'tgi', label: 'HuggingFace TGI' }, { value: 'tensorrt', label: 'TensorRT-LLM' }, { value: 'ollama', label: 'Ollama' }, { value: 'exllama', label: 'ExLlamaV2' }, { value: 'llamacpp', label: 'llama.cpp' }, { value: 'openai', label: 'OpenAI API' }, { value: 'custom', label: 'Custom' }], required: true },
      { key: 'batchSize', label: 'Batch Size', type: 'number', placeholder: '1' },
      { key: 'precision', label: 'Precision', type: 'select', options: [{ value: 'fp32', label: 'FP32' }, { value: 'fp16', label: 'FP16' }, { value: 'int8', label: 'INT8' }, { value: 'int4', label: 'INT4 (GPTQ/AWQ)' }, { value: 'bf16', label: 'BF16' }] },
      { key: 'maxTokens', label: 'Max Tokens', type: 'number', placeholder: '1024' },
      { key: 'temperature', label: 'Temperature', type: 'text', placeholder: '0.7' },
      { key: 'topP', label: 'Top-P', type: 'text', placeholder: '0.9' },
      { key: 'topK', label: 'Top-K', type: 'number', placeholder: '40' },
      { key: 'repetitionPenalty', label: 'Repetition Penalty', type: 'text', placeholder: '1.1' },
      { key: 'stopTokens', label: 'Stop Tokens', type: 'text', placeholder: 'comma separated, e.g. <|end|>, <|eot_id|>' },
      { key: 'contextLength', label: 'Context Length', type: 'number', placeholder: '4096' },
      { key: 'concurrentRequests', label: 'Max Concurrent Requests', type: 'number', placeholder: '1' },
    ],
    inputHint: 'Prompt text, input image, or tensor',
    inputPlaceholder: 'Paste input prompt or JSON',
    outputHint: 'Output format, max latency (ms), min throughput (req/s)',
    verificationOptions: [
      { value: 'zk-proof', label: 'ZK Proof (zkML)' },
      { value: 'hash-check', label: 'Output Hash Check' },
    ],
  },
  'AI Training': {
    label: 'AI Training',
    color: '#4ade80',
    fields: [
      { key: 'modelArchitecture', label: 'Model Architecture', type: 'text', placeholder: 'Llama-2-7B, YOLOv8', required: true },
      { key: 'framework', label: 'Framework', type: 'select', options: [{ value: 'pytorch', label: 'PyTorch' }, { value: 'tensorflow', label: 'TensorFlow' }, { value: 'jax', label: 'JAX' }, { value: 'axolotl', label: 'Axolotl' }, { value: 'unsloth', label: 'Unsloth' }, { value: 'transformers', label: 'HuggingFace Transformers' }], required: true },
      { key: 'trainingType', label: 'Training Type', type: 'select', options: [{ value: 'full', label: 'Full Fine-tune' }, { value: 'lora', label: 'LoRA' }, { value: 'qlora', label: 'QLoRA' }, { value: 'pretrain', label: 'Pre-training from scratch' }, { value: 'continued', label: 'Continued pre-training' }], required: true },
      { key: 'epochs', label: 'Epochs', type: 'number', placeholder: '50', required: true },
      { key: 'batchSize', label: 'Batch Size', type: 'number', placeholder: '64' },
      { key: 'learningRate', label: 'Learning Rate', type: 'text', placeholder: '1e-4' },
      { key: 'optimizer', label: 'Optimizer', type: 'select', options: [{ value: 'adam', label: 'Adam' }, { value: 'adamw', label: 'AdamW' }, { value: 'sgd', label: 'SGD' }, { value: 'lion', label: 'Lion' }, { value: 'adafactor', label: 'Adafactor' }] },
      { key: 'lossFunction', label: 'Loss Function', type: 'text', placeholder: 'e.g. cross-entropy, contrastive' },
      { key: 'precision', label: 'Precision', type: 'select', options: [{ value: 'fp32', label: 'FP32' }, { value: 'fp16', label: 'FP16' }, { value: 'bf16', label: 'BF16' }, { value: 'int8', label: 'INT8 (QLoRA)' }] },
      { key: 'numGPUs', label: 'Number of GPUs', type: 'number', placeholder: '4' },
      { key: 'datasetSize', label: 'Dataset Size', type: 'text', placeholder: 'e.g. 100GB, 1M samples' },
      { key: 'validationSplit', label: 'Validation Split', type: 'text', placeholder: 'e.g. 0.1' },
      { key: 'warmupSteps', label: 'Warmup Steps', type: 'number', placeholder: '100' },
      { key: 'weightDecay', label: 'Weight Decay', type: 'text', placeholder: '0.01' },
      { key: 'gradientCheckpointing', label: 'Gradient Checkpointing', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'no', label: 'No' }] },
    ],
    inputHint: 'Dataset URL, base model checkpoint',
    inputPlaceholder: 'https://... or ipfs://...',
    outputHint: 'Target accuracy/loss, model weights format',
    verificationOptions: [
      { value: 'hash-check', label: 'Weight Hash (off-chain)' },
      { value: 'manual-review', label: 'Manual Review' },
    ],
  },
  'Data Labeling': {
    label: 'Data Labeling',
    color: '#fbbf24',
    fields: [
      { key: 'taskType', label: 'Task Type', type: 'select', options: [{ value: 'classification', label: 'Image Classification' }, { value: 'bbox', label: 'Bounding Box' }, { value: 'segmentation', label: 'Segmentation (polygon)' }, { value: 'ner', label: 'Named Entity Recognition' }, { value: 'sentiment', label: 'Sentiment Analysis' }, { value: 'transcription', label: 'Audio Transcription' }, { value: 'translation', label: 'Translation Pair' }, { value: 'keypoint', label: 'Keypoint / Landmark' }], required: true },
      { key: 'labelSchema', label: 'Label Schema', type: 'text', placeholder: 'cat, dog, bird (comma separated)', required: true },
      { key: 'datasetSize', label: 'Dataset Size (items)', type: 'number', placeholder: '10000' },
      { key: 'annotationFormat', label: 'Output Format', type: 'select', options: [{ value: 'coco', label: 'COCO JSON' }, { value: 'yolo', label: 'YOLO TXT' }, { value: 'pascal', label: 'Pascal VOC XML' }, { value: 'csv', label: 'CSV' }, { value: 'jsonl', label: 'JSONL' }, { value: 'conll', label: 'CoNLL' }] },
      { key: 'minAnnotations', label: 'Min Annotations per Item', type: 'number', placeholder: '1' },
      { key: 'reviewRatio', label: 'Review / QA Ratio', type: 'text', placeholder: 'e.g. 20%' },
      { key: 'qualityThreshold', label: 'Quality Threshold', type: 'text', placeholder: 'e.g. agreement > 0.9' },
    ],
    inputHint: 'Dataset (images/text/audio), label taxonomy file',
    inputPlaceholder: 'Upload dataset or paste URL',
    outputHint: 'Annotated dataset format (COCO/JSON/CSV), agreement threshold',
    verificationOptions: [
      { value: 'manual-review', label: 'Manual Sampling Review' },
      { value: 'hash-check', label: 'Dataset Hash Check' },
    ],
  },
  'Video Transcoding': {
    label: 'Video Transcoding',
    color: '#fb7185',
    fields: [
      { key: 'codec', label: 'Video Codec', type: 'select', options: [{ value: 'h264', label: 'H.264' }, { value: 'h265', label: 'H.265/HEVC' }, { value: 'vp9', label: 'VP9' }, { value: 'av1', label: 'AV1' }, { value: 'avc', label: 'AVC (Intra)' }, { value: 'prores', label: 'Apple ProRes' }], required: true },
      { key: 'crf', label: 'CRF / Quality', type: 'number', placeholder: '23' },
      { key: 'preset', label: 'Encoding Preset', type: 'select', options: [{ value: 'ultrafast', label: 'UltraFast' }, { value: 'fast', label: 'Fast' }, { value: 'medium', label: 'Medium' }, { value: 'slow', label: 'Slow' }, { value: 'veryslow', label: 'VerySlow' }] },
      { key: 'resolution', label: 'Output Resolution', type: 'text', placeholder: '1920x1080' },
      { key: 'fps', label: 'Output FPS', type: 'number', placeholder: '30' },
      { key: 'bitrate', label: 'Target Bitrate', type: 'text', placeholder: 'e.g. 5M, 10M' },
      { key: 'audioCodec', label: 'Audio Codec', type: 'select', options: [{ value: 'aac', label: 'AAC' }, { value: 'mp3', label: 'MP3' }, { value: 'opus', label: 'Opus' }, { value: 'flac', label: 'FLAC (lossless)' }, { value: 'ac3', label: 'AC-3 (Dolby)' }] },
      { key: 'audioBitrate', label: 'Audio Bitrate', type: 'text', placeholder: 'e.g. 128k, 320k' },
      { key: 'hdrFormat', label: 'HDR Format', type: 'select', options: [{ value: 'none', label: 'SDR' }, { value: 'hdr10', label: 'HDR10' }, { value: 'hlg', label: 'HLG' }, { value: 'dolby', label: 'Dolby Vision' }] },
      { key: 'deinterlace', label: 'Deinterlace', type: 'select', options: [{ value: 'no', label: 'No' }, { value: 'yes', label: 'Yes (bwdif)' }, { value: 'yadif', label: 'Yes (yadif)' }] },
      { key: 'segmentDuration', label: 'Segment Duration (for HLS)', type: 'number', placeholder: '10' },
      { key: 'cropFilter', label: 'Crop / Padding', type: 'text', placeholder: 'e.g. 1920:800:0:140' },
    ],
    inputHint: 'Source video URL or file',
    inputPlaceholder: 'Upload video or paste URL',
    outputHint: 'Output format specs, SSIM/PSNR threshold',
    verificationOptions: [
      { value: 'hash-check', label: 'Perceptual Hash (SSIM)' },
      { value: 'manual-review', label: 'Manual Spot Check' },
    ],
  },
  Scientific: {
    label: 'Scientific Simulation',
    color: '#67e8f9',
    fields: [
      { key: 'engine', label: 'Simulation Engine', type: 'select', options: [{ value: 'gromacs', label: 'GROMACS' }, { value: 'namd', label: 'NAMD' }, { value: 'alphafold2', label: 'AlphaFold2' }, { value: 'rosetta', label: 'Rosetta' }, { value: 'lammps', label: 'LAMMPS' }, { value: 'vasp', label: 'VASP' }, { value: 'gaussian', label: 'Gaussian' }, { value: 'openmm', label: 'OpenMM' }, { value: 'espresso', label: 'Quantum ESPRESSO' }], required: true },
      { key: 'forceField', label: 'Force Field / Functional', type: 'text', placeholder: 'AMBER99SB-ILDN, PBE, CHARMM36' },
      { key: 'simulationSteps', label: 'Simulation Steps', type: 'number', placeholder: '1000000', required: true },
      { key: 'simulationTime', label: 'Total Simulation Time', type: 'text', placeholder: 'e.g. 500ns, 10ps' },
      { key: 'temperature', label: 'Temperature (K)', type: 'text', placeholder: '300' },
      { key: 'pressure', label: 'Pressure (atm/bar)', type: 'text', placeholder: '1.0' },
      { key: 'ensemble', label: 'Ensemble', type: 'select', options: [{ value: 'nvt', label: 'NVT' }, { value: 'npt', label: 'NPT' }, { value: 'nve', label: 'NVE' }, { value: 'nph', label: 'NPH' }] },
      { key: 'solventModel', label: 'Solvent Model', type: 'select', options: [{ value: 'explicit', label: 'Explicit (TIP3P/SPC)' }, { value: 'implicit', label: 'Implicit (GB/SA)' }, { value: 'vacuum', label: 'Vacuum' }] },
      { key: 'ensembleRuns', label: 'Number of Ensemble Runs', type: 'number', placeholder: '1' },
      { key: 'outputInterval', label: 'Output Write Interval', type: 'number', placeholder: '1000' },
    ],
    inputHint: 'PDB file, topology, or sequence (FASTA)',
    inputPlaceholder: 'Upload .pdb / .top file or paste sequence',
    outputHint: 'Energy threshold (kcal/mol), RMSD, trajectory format',
    verificationOptions: [
      { value: 'hash-check', label: 'Energy Comparison (off-chain)' },
      { value: 'manual-review', label: 'Scientific Review' },
    ],
  },
  'RAG Pipeline': {
    label: 'RAG Pipeline',
    color: '#c084fc',
    fields: [
      { key: 'chunkStrategy', label: 'Chunk Strategy', type: 'select', options: [{ value: 'recursive', label: 'Recursive Character' }, { value: 'semantic', label: 'Semantic Splitting' }, { value: 'fixed', label: 'Fixed Size' }, { value: 'markdown', label: 'Markdown Header' }, { value: 'recursive-json', label: 'Recursive JSON' }, { value: 'agentic', label: 'Agentic (LLM-based)' }], required: true },
      { key: 'chunkSize', label: 'Chunk Size (tokens)', type: 'number', placeholder: '512' },
      { key: 'chunkOverlap', label: 'Chunk Overlap', type: 'number', placeholder: '128' },
      { key: 'embeddingModel', label: 'Embedding Model', type: 'text', placeholder: 'text-embedding-3-small', required: true },
      { key: 'retrieverType', label: 'Retriever Type', type: 'select', options: [{ value: 'vector', label: 'Vector Search' }, { value: 'hybrid', label: 'Hybrid (vector + BM25)' }, { value: 'bm25', label: 'BM25 Keyword' }, { value: 'multi-vector', label: 'Multi-Vector (MMR)' }] },
      { key: 'topK', label: 'Top K Retrieval', type: 'number', placeholder: '5' },
      { key: 'reranker', label: 'Reranker Model', type: 'text', placeholder: 'e.g. cohere-rerank, bge-reranker' },
      { key: 'hybridSearch', label: 'Hybrid Search Alpha', type: 'text', placeholder: '0.5 (0=BM25, 1=vector)' },
      { key: 'maxContextLength', label: 'Max Context Length', type: 'number', placeholder: '4096' },
      { key: 'systemPrompt', label: 'System Prompt', type: 'textarea', placeholder: 'You are a helpful assistant...' },
    ],
    inputHint: 'Documents (PDF/HTML/markdown), query examples',
    inputPlaceholder: 'Upload documents or paste URL',
    outputHint: 'Index size, retrieval latency, recall@K threshold',
    verificationOptions: [
      { value: 'hash-check', label: 'Index Hash Check' },
      { value: 'manual-review', label: 'Query Golden Set Evaluation' },
    ],
  },
  FHE: {
    label: 'FHE Computation',
    color: '#f472b6',
    fields: [
      { key: 'scheme', label: 'FHE Scheme', type: 'select', options: [{ value: 'bfv', label: 'BFV (integer)' }, { value: 'bgv', label: 'BGV (integer)' }, { value: 'ckks', label: 'CKKS (floating point)' }, { value: 'tfhe', label: 'TFHE (boolean)' }], required: true },
      { key: 'library', label: 'Library', type: 'select', options: [{ value: 'openfhe', label: 'OpenFHE' }, { value: 'seal', label: 'Microsoft SEAL' }, { value: 'helib', label: 'IBM HELib' }, { value: 'tfhe-rs', label: 'TFHE-rs' }, { value: 'concrete', label: 'Zama Concrete' }], required: true },
      { key: 'polyDegree', label: 'Polynomial Degree', type: 'number', placeholder: '4096', required: true },
      { key: 'plainModulus', label: 'Plain Modulus', type: 'text', placeholder: '65537' },
      { key: 'scaleModulus', label: 'Scale Modulus', type: 'text', placeholder: '1e6' },
      { key: 'multiplicationDepth', label: 'Multiplication Depth', type: 'number', placeholder: '4' },
      { key: 'securityLevel', label: 'Security Level', type: 'select', options: [{ value: '128', label: '128-bit' }, { value: '192', label: '192-bit' }, { value: '256', label: '256-bit' }] },
      { key: 'batchSize', label: 'Batch / Slot Size', type: 'number', placeholder: '1' },
      { key: 'noiseBudget', label: 'Initial Noise Budget', type: 'number', placeholder: '40' },
      { key: 'bootstrapType', label: 'Bootstrapping', type: 'select', options: [{ value: 'none', label: 'None' }, { value: 'automatic', label: 'Auto (if needed)' }, { value: 'manual', label: 'Manual (specify intervals)' }] },
      { key: 'accelHardware', label: 'Acceleration Hardware', type: 'select', options: [{ value: 'cpu', label: 'CPU only' }, { value: 'gpu-cuda', label: 'GPU (CUDA)' }, { value: 'gpu-rocm', label: 'GPU (ROCm)' }, { value: 'fpga', label: 'FPGA' }] },
    ],
    inputHint: 'Ciphertext or public key to process',
    inputPlaceholder: 'Paste ciphertext (hex) or upload file',
    outputHint: 'Ciphertext result, minimum noise budget threshold',
    verificationOptions: [
      { value: 'zk-proof', label: 'Decryption ZK Proof' },
      { value: 'hash-check', label: 'Noise Budget Check' },
    ],
  },
  Custom: {
    label: 'Custom',
    color: '#a855f7',
    fields: [],
    inputHint: 'Describe what input is needed',
    inputPlaceholder: 'Input specification...',
    outputHint: 'Describe expected output format',
    verificationOptions: [
      { value: 'manual-review', label: 'Manual Review' },
      { value: 'hash-check', label: 'Hash Check' },
    ],
  },
}

// Additional suggested job types that fit the verifiable compute model.
// These can be added to expand beyond pure "computation".
// Each should support one of the existing verificationOptions (hash-check, manual-review, zk-proof).

export const SUGGESTED_ADDITIONAL_TYPES = {
  'Audio Processing': {
    label: 'Audio / Speech Processing',
    color: '#f43f5e',
    fields: [
      { key: 'task', label: 'Task', type: 'select', options: [
        { value: 'stt', label: 'Speech-to-Text' }, 
        { value: 'tts', label: 'Text-to-Speech' }, 
        { value: 'enhancement', label: 'Audio Enhancement' },
        { value: 'diarization', label: 'Speaker Diarization' }
      ], required: true },
      { key: 'model', label: 'Model / Engine', type: 'text', placeholder: 'whisper-large, coqui-tts' },
      { key: 'sampleRate', label: 'Sample Rate', type: 'number', placeholder: '16000' },
      { key: 'language', label: 'Language', type: 'text', placeholder: 'en, id, multi' },
    ],
    inputHint: 'Audio file URL (wav/mp3) or transcript',
    inputPlaceholder: 'https://... or ipfs://...',
    outputHint: 'Transcript JSON, audio file hash, WER/CER threshold',
    verificationOptions: [
      { value: 'hash-check', label: 'Output Hash + WER Check' },
      { value: 'manual-review', label: 'Manual Transcript Review' },
      { value: 'zk-proof', label: 'ZK Proof of Correct Transcription (advanced)' },
    ],
  },

  'Image Generation': {
    label: 'Image / Vision Generation',
    color: '#a78bfa',
    fields: [
      { key: 'model', label: 'Model', type: 'text', placeholder: 'stable-diffusion-xl, flux', required: true },
      { key: 'resolution', label: 'Resolution', type: 'select', options: [{ value: '512x512', label: '512x512' }, { value: '1024x1024', label: '1024x1024' }, { value: '1024x576', label: '16:9' }], required: true },
      { key: 'steps', label: 'Inference Steps', type: 'number', placeholder: '30' },
      { key: 'guidanceScale', label: 'Guidance Scale', type: 'text', placeholder: '7.5' },
      { key: 'seed', label: 'Seed (optional for reproducibility)', type: 'text' },
    ],
    inputHint: 'Text prompt + optional reference image / mask',
    inputPlaceholder: 'A cyberpunk city at night...',
    outputHint: 'Generated image hash, CLIP score, or perceptual similarity threshold',
    verificationOptions: [
      { value: 'hash-check', label: 'Image Hash + Perceptual Hash' },
      { value: 'manual-review', label: 'Manual Quality Review' },
    ],
  },

  'Smart Contract Audit': {
    label: 'Smart Contract Audit & Formal Verification',
    color: '#f97316',
    fields: [
      { key: 'language', label: 'Language', type: 'select', options: [{ value: 'solidity', label: 'Solidity' }, { value: 'vyper', label: 'Vyper' }, { value: 'move', label: 'Move' }], required: true },
      { key: 'toolchain', label: 'Tools Used', type: 'text', placeholder: 'Slither, Mythril, Certora, Foundry' },
      { key: 'contractSize', label: 'Contract Size (LOC or bytecode)', type: 'text' },
      { key: 'focusAreas', label: 'Focus Areas', type: 'text', placeholder: 'Reentrancy, access control, math' },
    ],
    inputHint: 'Source code (Solidity) + test suite or deployment address',
    inputPlaceholder: 'Paste contract code or GitHub link',
    outputHint: 'Audit report hash, vulnerability count, formal proof artifacts',
    verificationOptions: [
      { value: 'manual-review', label: 'Auditor Report Review' },
      { value: 'hash-check', label: 'Report + Bytecode Hash' },
    ],
  },

  'Data Anonymization': {
    label: 'Data Anonymization & Privacy',
    color: '#14b8a6',
    fields: [
      { key: 'technique', label: 'Technique', type: 'select', options: [
        { value: 'k-anonymity', label: 'k-Anonymity' },
        { value: 'differential-privacy', label: 'Differential Privacy' },
        { value: 'synthetic', label: 'Synthetic Data Generation' },
        { value: 'federated', label: 'Federated Anonymization' }
      ], required: true },
      { key: 'epsilon', label: 'Privacy Budget (ε)', type: 'text', placeholder: '1.0' },
      { key: 'kValue', label: 'k Value (for k-anonymity)', type: 'number', placeholder: '5' },
    ],
    inputHint: 'Raw dataset (CSV/Parquet) + schema',
    inputPlaceholder: 'Upload or link to dataset',
    outputHint: 'Anonymized dataset hash, privacy metrics (epsilon, k, utility loss)',
    verificationOptions: [
      { value: 'hash-check', label: 'Dataset Hash + Privacy Metrics' },
      { value: 'manual-review', label: 'Sample Review + Metric Validation' },
    ],
  },

  'LLM Evaluation': {
    label: 'LLM Evaluation & Benchmarking',
    color: '#eab308',
    fields: [
      { key: 'benchmark', label: 'Benchmark Suite', type: 'select', options: [
        { value: 'mmlu', label: 'MMLU' }, 
        { value: 'humaneval', label: 'HumanEval' }, 
        { value: 'gsm8k', label: 'GSM8K' },
        { value: 'custom', label: 'Custom Eval Set' }
      ], required: true },
      { key: 'modelVersion', label: 'Model Version', type: 'text', placeholder: 'gpt-4o, llama-3-70b' },
      { key: 'numSamples', label: 'Number of Samples', type: 'number', placeholder: '1000' },
      { key: 'metrics', label: 'Metrics', type: 'text', placeholder: 'accuracy, pass@k, bleu' },
    ],
    inputHint: 'Evaluation dataset + model endpoint or weights',
    inputPlaceholder: 'Dataset URL or HuggingFace dataset',
    outputHint: 'Score report, benchmark hash, statistical significance',
    verificationOptions: [
      { value: 'hash-check', label: 'Eval Set Hash + Score Verification' },
      { value: 'manual-review', label: 'Human Evaluation Sampling' },
    ],
  },
}

export const JOB_TYPE_OPTIONS = Object.entries(JOB_TYPE_CONFIGS).map(([value, config]) => ({
  value,
  label: config.label,
}))

// Helper to get all available types (core + suggested)
export const ALL_JOB_TYPES = {
  ...JOB_TYPE_CONFIGS,
  ...SUGGESTED_ADDITIONAL_TYPES,
}
